name: push
on: ["push"]
env:
  COMPUTED_GIT_TAG: ${{ github.ref_name == github.event.repository.default_branch && 'latest' || 'testing' }}
jobs:

  collect-metadata:
    runs-on: ubuntu-latest
    steps:
      - id: repo-name
        run: |
          echo "repository_name=${GITHUB_REPOSITORY#*/}" >>"$GITHUB_OUTPUT"
    outputs:
      repo_name: ${{ steps.repo-name.outputs.repository_name }}
      
  publish-docker:
    needs: collect-metadata
    concurrency:
      group: ${{ github.repository }}
    env:
      REPO_NAME: ${{ needs.collect-metadata.outputs.repo_name }}
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ github.token }}"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-session-name: github
          role-to-assume: ${{ secrets.ECR_ROLE }}
      - uses: aws-actions/amazon-ecr-login@v2
      - uses: docker/build-push-action@v6
        with:
          build-args: "repo_name=${{ env.REPO_NAME }}"
          #cache-from: "type=registry,ref=ghcr.io/${{ github.repository }}:buildcache"
          cache-to: "type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max"
          context: .
          platforms: linux/arm/v5,linux/arm64,linux/amd64
          provenance: 'false'
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.COMPUTED_GIT_TAG }}
            ${{ secrets.ECR_URL }}:${{ env.REPO_NAME }}-${{ env.COMPUTED_GIT_TAG }}
